# Generated by Django 3.2.15 on 2023-01-04 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_defect', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File_upload',
            new_name='File_upload_table',
        ),
    ]
