# Generated by Django 3.2.15 on 2023-01-04 09:39

import bottle_defect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_defect', '0002_rename_file_upload_file_upload_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload_table',
            name='images',
            field=models.FileField(upload_to=bottle_defect.models.upload_path),
        ),
    ]
