# Generated by Django 3.2.15 on 2023-01-05 04:48

import bottle_defect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_defect', '0003_alter_file_upload_table_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='content_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_val', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='file_upload_table',
            name='images',
            field=models.ImageField(upload_to=bottle_defect.models.upload_path),
        ),
    ]
