# Generated by Django 3.2.15 on 2023-01-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_defect', '0007_remove_uploaded_file_detail_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaded_file_detail',
            name='batch_name',
        ),
        migrations.RemoveField(
            model_name='uploaded_file_detail',
            name='upload_time',
        ),
    ]
