# Generated by Django 3.2.15 on 2023-01-06 12:52

import bottle_defect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_defect', '0008_auto_20230106_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_file_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, default='/Images/None/No-img.jpg', max_length=255, upload_to=bottle_defect.models.upload_path)),
                ('batch_name', models.CharField(max_length=100)),
                ('upload_time', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='uploaded_file_detail',
        ),
    ]
