# Generated by Django 3.2.15 on 2023-01-09 10:36

import bottle_defect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_defect', '0009_auto_20230106_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_file_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('images', models.ImageField(blank=True, max_length=255, upload_to=bottle_defect.models.upload_path)),
                ('upload_time', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='upload_file_detail',
        ),
    ]
