# Generated by Django 3.2.15 on 2023-01-10 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_defect', '0010_auto_20230109_1606'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='upload_file_details',
            new_name='upload_image',
        ),
    ]
