# Generated by Django 3.2.15 on 2023-01-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_defect', '0011_rename_upload_file_details_upload_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
