# Generated by Django 3.2.15 on 2023-01-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottle_defect', '0012_upload_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_image',
            name='Analysis',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
